---

- name: Check if old conf is exist
  #stat:
  #  path: "{{ nginx_conf_dir }}/{{ item['server']['file_name'] }}.conf"
  shell: "ls {{ nginx_conf_dir }}/vhost/{{ item['server']['file_name'] }}.conf"
  ignore_errors: True
  with_items:
    - "{{ nginx_sites }}"
  when: nginx_sites|lower != 'none'
  register: conf_file_exist

- name: Backup old conf file if exist
  archive:
    path: "{{ nginx_conf_dir }}/vhost/{{ item['server']['file_name'] }}.conf"
    dest: "{{ nginx_conf_dir }}/vhost/{{ item['server']['file_name'] }}.conf-{{ lookup('pipe','date +%Y%m%d%H%M%S') }}.backup.tar.gz"
  with_items:
    - "{{ nginx_sites }}"
  when: conf_file_exist is succeeded

- name: Create the configurations for sites
  template:
    src:  app.conf.j2
    dest: "{{ nginx_conf_dir }}/vhost/{{ item['server']['file_name'] }}.conf"
    backup: yes
  with_items:
    - "{{ nginx_sites }}"
  when: nginx_sites|lower != 'none'

- name: Update LB_method
  shell: "sed -i 's/#LB_method/{{ LB_method }}/g' {{ nginx_conf_dir }}/vhost/{{ item['server']['file_name'] }}.conf"
  with_items:
    - "{{ nginx_sites }}"
  when: LB_method != 'DEFAULT' and nginx_sites|lower != 'none'