---
# defaults file for tomcat-ansible-role
# tomcat部署时主配置文件

tomcat_major_version: "{{ tomcat_version.split('.')[0].tomcat_version.split('.')[1] }}"

tomcat_install_java: False
tomcat_java_version: 1.8.0_201
tomcat_java_home: /data/soft/jdk1.8.0_201

tomcat_java_packages_EL:
 - {package: "java-{{ tomcat_java_version }}{% if '1.' in tomcat_java_version|string %}.0{% endif %}-openjdk"}

tomcat_package_source: local
tomcat_downloadURL: https://archive.apache.org/dist
tomcat_temp_download_path: /tmp/ansible/tomcat/tempdir

tomcat_user: www
tomcat_group: www

tomcat_install_path: /data/service

# tomcat的绝对路径
tomcat_complete_path: "{{ tomcat_install_path }}/{% if tomcat_dir_name == 'NULL' %}apache-tomcat-{{ tomcat_version }}{% else %}{{ tomcat_dir_name }}{% endif %}"
clean_all_webapps: True
# JVM的相关配置，单位为m
tomcat_jvm_memory_percentage_xms: 512
tomcat_jvm_memory_percentage_xmx: 512

tomcat_permissions_production: False
tomcat_webapps_auto_deployment: True
tomcat_permissions_ensure_on_every_run: True

tomcat_allow_manager_access_only_from_localhost: False
tomcat_allow_host_manager_access_only_from_localhost: False

tomcat_debug_mode: False


tomcat_port_ajp: 8009
tomcat_port_debug: 8000

tomcat_users: []

tomcat_user_roles: []


# Uninstall default parameters
tomcat_uninstall_create_backup: True
tomcat_backup_path: /data/backup
tomcat_uninstall_remove_user: False
tomcat_uninstall_remove_group: False
tomcat_uninstall_remove_java: False