---

#- name: startup jar
#  shell: "sh {{ script_pash }}/start.sh"

# 启动应用 换成shell命令启动，避免shell脚本远程不执行的情况
- name: startup jar
  shell: "source /etc/profile && nohup java -Xms{{ jvm_Xms }}M -Xmx{{ jvm_Xmx }}M -jar {{ script_pash }}/{{ jar_name }}-1.0.0.jar > /dev/null 2>&1 &"

- name: restart jar
  shell: "sh {{ script_pash }}/stop.sh && sleep 5 && sh {{ script_pash }}/start.sh"