---
# 配置文件以及日志文件路径
- name: Create the directories for site specific configurations
  file:
    path: "{{ nginx_conf_dir }}/{{ item }}"
    state: directory
    owner: "{{ nginx_conf_user }}"
    group: "{{ nginx_conf_group }}"
    mode: "{{ nginx_dir_perm }}"
  with_items:
    - "{{ nginx_conf_subdirectory }}"

- name: Ensure log directory exist
  file:
    path: "{{ nginx_log_dir }}"
    state: directory
    owner: "{{ nginx_log_user }}"
    group: "{{ nginx_log_group }}"
    mode: "{{ nginx_log_perm }}"

- name: Ensure backup directory exist
  file:
    path: "{{ app_backup_path }}/{{ nginx_site_name }}"
    state: directory
    owner: "{{ nginx_log_user }}"
    group: "{{ nginx_log_group }}"
    mode: "{{ nginx_log_perm }}"