---
# Rollback jar


- name: Get the latest backup file
  shell: "ls -lt {{ back_directory }}/{{ jar_name }}/*backup*|head -n 1|awk '{print$9}'"
  register: backfile_path

- name: (deplay) Check if {{ jar_name }} service is running
  shell: "ps -ef|grep -w {{ jar_name }}-1.0.0.jar |grep -v grep|wc -l"
  register: service_running
  
- name: 获取jar包运行的pid
  shell: "ps -ef |grep -v grep |grep -w {{ jar_name }}-1.0.0.jar|awk '{print $2}'"
  when: service_running.stdout|int >= 1
  register: running_processes

# 强制杀死进程
- name: Force kill stuck processes
  shell: "kill -9 {{ item }}"
  with_items: "{{ running_processes.stdout_lines }}"
  when: service_running.stdout|int >= 1
  register: service_is_stop

- name: remove jar file
  file:
    path: "{{ script_pash }}/{{ jar_name }}-1.0.0.jar"
    state: absent

- name: rollback jar file from backup file
  unarchive:
    src: "{{ backfile_path.stdout }}"
    dest: "{{ script_pash }}/"
    remote_src: yes
  notify: startup jar
